#!/bin/bash


echo ============================================================
echo                      Smart Rooms Installer
echo ============================================================

echo ==================  Install Mosquitto Repo  =====================
if [ ! -f "/etc/apt/sources.list.d/mosquitto-stretch.list" ]
then
	wget http://repo.mosquitto.org/debian/mosquitto-repo.gpg.key
	sudo apt-key add mosquitto-repo.gpg.key
	rm mosquitto-repo.gpg.key
	cd /etc/apt/sources.list.d/
	sudo wget http://repo.mosquitto.org/debian/mosquitto-stretch.list
	cd ~
fi

echo ==================  Install nginx Repo  =====================
if [ ! -f "/etc/apt/sources.list.d/nginx-stretch.list" ]
then
	wget https://nginx.org/keys/nginx_signing.key
	sudo apt-key add nginx_signing.key
	rm nginx_signing.key
	cd /etc/apt/sources.list.d/
	sudo sh -c /
'echo "deb http://nginx.org/packages/debian/ stretch nginx
deb-src http://nginx.org/packages/debian/ stretch nginx" > nginx-stretch.list'
	cd ~
fi

echo ==================  System Update  =====================
sudo apt-get --assume-yes update

echo ==================  Install HOSTAPD, DNSMASQ, MOSQUITTO and NGINX  =====================
sudo apt-get --assume-yes install hostapd
sudo apt-get --assume-yes install dnsmasq
sudo apt-get --assume-yes install mosquitto
sudo apt-get --assume-yes install ntp
sudo apt-get --assume-yes install nginx

echo ================== Configure NTP Server  =====================
sudo  sh -c 'echo "server 10.103.0.1 prefer" > /etc/ntp.conf'
sudo service ntp restart

echo ================== Configure Mosquitto Conf===================
sudo  sh -c 'echo "listener 9001
protocol websockets" > /etc/mosquitto/conf.d/mosq.conf'


echo ================== Create backup config files  =====================
hostapdconf="/etc/hostapd/hostapd.conf"
dnsmasqconf="/etc/dnsmasq.conf"
dhcpcdconf="/etc/dhcpcd.conf"
conffiles=($hostapdconf $dnsmasqconf $dhcpcdconf)
for conf in "${conffiles[@]}"
do
        if [ -f conf ] && [ ! -f "$conf.old" ]
        then
		echo 
		echo ==== Move  $conf ====
		sudo mv $conf "$conf.old"
        fi
done

echo ===================== Remove old config files  =====================
for conf in "${conffiles[@]}"
do
        if [ -f conf ] && [ ! -f "$conf.old" ]
        then
		echo 
		echo ==== rm  $conf ====
		sudo rm $conf
	fi
done

echo ===================== Create /etc/dhcpcd.conf =====================
if [ -f "/etc/dhcpcd.conf" ]
then
	sudo rm /etc/dhcpcd.conf
fi
sudo sh -c \
'echo " 
interface uap0
	static ip_address=10.103.0.1/24
	nohook wpa_supplicant
" >> /etc/dhcpcd.conf'

echo ===================== Create /etc/dnsmasq.conf ====================
if [ -f "/etc/dnsmasq.conf" ]
then
	sudo rm /etc/dnsmasq.conf
fi
sudo sh -c \
'echo "interface=uap0
dhcp-range=10.103.0.2,10.103.0.255,255.255.255.0,24h
" >> /etc/dnsmasq.conf'

echo ===================== Create /etc/hostapd/hostapd.conf ============
if [ -f "/etc/hostapd/hostapd.conf" ]
then
	sudo rm /etc/hostapd/hostapd.conf 
fi 
sudo sh -c \ 
'echo "interface=uap0 driver=nl80211 ssid=SRCentral hw_mode=g channel=11 macaddr_acl=0 auth_algs=1 wpa=2 wpa_key_mgmt=WPA-PSK ignore_broadcast_ssid=0 
wpa_psk=aec9bf48e9b1245b95aaf8b9e8b6e4102e234810317f1492856c783d3975ff2d rsn_pairwise=CCMP wpa_pairwise=TKIP" >> /etc/hostapd/hostapd.conf'

echo ================== Create sensorstartnet file ===================== if [ -f "/etc/network/if-up.d/sensorstartnet" ] then
	sudo rm /etc/network/if-up.d/sensorstartnet fi

sudo sh -c \ 'echo "#!/bin/sh -e

if [ \"\$IFACE\" = lo ]; then
	exit 0 fi iw dev wlan0 interface add uap0 type __ap ip addr add 10.103.0.1/24 dev uap0

hostapd -B /etc/hostapd/hostapd.conf

/etc/init.d/dhcpcd restart

" >> /etc/network/if-up.d/sensorstartnet'

sudo chmod 755 /etc/network/if-up.d/sensorstartnet


 
