#!/bin/bash
echo =======================================================================
echo ==                       CONFIGURE WEBSERVER                         ==
echo =======================================================================
echo 

echo ========== Download NODEJS ============================================

NODEVERSION="v10.8.0"
DISTRO="linux-armv7l"

if [ -d "/usr/local/lib/nodejs" ]
then 
	sudo rm -rf /usr/local/lib/nodejs
fi

sudo mkdir /usr/local/lib/nodejs
if [ ! -f node-$NODEVERSION-$DISTRO.tar.xz ]
then
	curl https://nodejs.org/dist/$NODEVERSION/node-$NODEVERSION-$DISTRO.tar.gz -o node-$NODEVERSION-$DISTRO.tar.xz
fi 

echo =======================================================================
echo ========== UNPACK NODE IN USER FOLDER =================================

sudo tar xvzf node-$NODEVERSION-$DISTRO.tar.xz -C /usr/local/lib/nodejs

sudo mv /usr/local/lib/nodejs/node-$NODEVERSION-$DISTRO /usr/local/lib/nodejs/node-$NODEVERSION

sudo rm -rf /usr/local/lib/nodejs/node-$NODEVERSION-$DISTRO

echo =======================================================================
echo ========== WRITE TO PROFILE ===========================================
sudo sh -c \
'echo "# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

# if running bash
if [ -n \"\$BASH_VERSION\" ]; then
    # include .bashrc if it exists
    if [ -f \"\$HOME/.bashrc\" ]; then
	. \"\$HOME/.bashrc\"
    fi
fi

# set PATH so it includes user s private bin if it exists
if [ -d \"\$HOME/bin\" ] ; then
    PATH=\"\$HOME/bin:\$PATH\"
fi

# NODEJS "'$NODEVERSION'"
export NODEJS_HOME=/usr/local/lib/nodejs/node-"'$NODEVERSION'"/bin
export PATH=\$NODEJS_HOME:\$PATH" > .profile'

echo =======================================================================
echo ========== REMOVE .profile file =======================================
if [ -f "~/.profile" ]; then
	sudo rm ~/.profile
fi

echo =======================================================================
echo ============ MOVE .profile file =======================================
sudo mv .profile ~/.profile

echo =======================================================================
echo =================== UPDATE PATH =======================================
export NODEJS_HOME=/usr/local/lib/nodejs/node-$NODEVERSION/bin
export PATH=\$NODEJS_HOME:\$PATH

